/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TInput: typeof import('tdesign-vue-next')['Input']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
